---
title: "TNBC-Subtypes"
output: 
  html_document: 
    toc: true
    toc_float:
      collapsed: false
    fig_width: 15
    fig_height: 6
---

```{r warning=FALSE, echo=FALSE, message=FALSE}
## Load package
library(magrittr)
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(Matrix)
# library(harmony)
library(openxlsx)
library(forestplot)
```

### Import data

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.width =8, fig.height =6}
load("SC_TNBC_Subtype.RData")
```

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
#SC1 <- subset(x = SC, subset= (FDR < 0.05))
table(SC1$prediction)
table(SC1$subtype,SC1$prediction)
table(SC1$celltype_subset,SC1$prediction)
table(SC1$celltype_major,SC1$prediction)
# table(SC1$Cell_subtype,SC1$prediction)
```

### Visualize predicted cells using UMAP 

<!-- ### Standard process -->

<!-- ```{r fig.height=5, fig.width=7, warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- SC2 <- SC -->
<!-- ## Normalizing -->
<!-- SC2 <- NormalizeData(SC2, normalization.method = "LogNormalize", scale.factor = 1e4) -->
<!-- ## Find highly variable features -->
<!-- SC2 <- FindVariableFeatures(SC2, selection.method = "vst", nfeatures = 2000) -->
<!-- ## Scaling the data -->
<!-- SC2 <- ScaleData(SC2, features = rownames(SC2)) -->
<!-- ``` -->

<!-- ```{r fig.height = 4.5, fig.width = 7,warning=FALSE, echo=FALSE, message=FALSE,results='hide'} -->
<!-- SC2 <- RunPCA(SC2, features = VariableFeatures(object = SC2), seed.use = 2021) -->
<!-- # ElbowPlot(SC2, ndims = 50, reduction = "pca") + -->
<!-- #   geom_hline(aes(yintercept = 1.5), colour = "Red") + -->
<!-- #   ggtitle(paste0("Elbow Plot - ", Project(SC2))) + -->
<!-- #   theme(plot.title = element_text(hjust = 0.5)) + -->
<!-- #   NULL -->
<!-- ``` -->

<!-- ```{r warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- pc.num.SC <- 1:30 -->
<!-- ``` -->

<!-- ```{r warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- ## UMAP -->
<!-- SC2 <- RunUMAP(SC2, reduction = "pca", -->
<!--                   dims = pc.num.SC, n.neighbors = 5, seed.use = 2021) -->
<!-- ``` -->

<!-- * Show the distribution of different samples without harmony -->

<!-- ```{r fig.height=6, fig.width=7.5,warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- SC2$celltype_major <- factor(SC2$celltype_major, -->
<!--                         levels = c("CAFs", "Cancer Epithelial","Normal Epithelial", "Myeloid", -->
<!--                                         "T-cells","B-cells","Endothelial","PVL","Plasmablasts")) -->

<!-- DimPlot(SC2, reduction = "umap", group.by = 'orig.ident', label = F, repel = T)  -->
<!-- ``` -->

<!-- *  Do the harmony to remove the batch effect -->

<!-- ```{r fig.height=4.5, fig.width=7,warning=FALSE, echo=FALSE, message=FALSE, results='hide'} -->
<!-- SC_harmony <- RunHarmony(SC2, dims.use = pc.num.SC, -->
<!--                          group.by.vars = "orig.ident", reduction = "pca") -->
<!-- # ElbowPlot(SC_harmony, ndims = 50, reduction = "harmony") + -->
<!-- #   geom_hline(aes(yintercept = 1.5), colour = "Red") + -->
<!-- #   ggtitle(paste0("Elbow Plot Harmony - ", Project(SC))) + -->
<!-- #   theme(plot.title = element_text(hjust = 0.5)) + -->
<!-- #   NULL -->
<!-- ``` -->

<!-- ```{r warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- pc.num.harmony.SC <- 1:30 -->
<!-- ``` -->

<!-- ```{r warning=FALSE, echo=FALSE, message=FALSE} -->
<!-- ## UMAP -->
<!-- SC_harmony <- RunUMAP(SC_harmony, reduction = "harmony", -->
<!--                          dims = pc.num.harmony.SC, n.neighbors = 5, seed.use = 2021, -->
<!--                          reduction.name = "umap.harmony", reduction.key = "UMAPharmony_") -->
<!-- #names(SC_harmony@reductions) -->
<!-- ``` -->

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height=6, fig.width=7.5}
DimPlot(SC_harmony, reduction = "umap.harmony", group.by = 'orig.ident', label = F) 
DimPlot(SC_harmony, reduction = "umap.harmony", group.by = 'celltype_major', label = F) 
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 6, fig.width = 12}
metadata <- SC_harmony@meta.data
temp <- data.frame(ID=SC1$ID,type=SC1$prediction)
meta <- merge(metadata,temp,by="ID",all = TRUE)
meta$type <- as.character(meta$type)
meta$type  <- ifelse(is.na(meta$type), "Undefined", meta$type)
rownames(meta) <- meta$ID
meta <- meta[SC_harmony$ID,]
SC_harmony <- AddMetaData(SC_harmony, metadata = meta)
  
pos <- SC_harmony@reductions[["umap.harmony"]]@cell.embeddings
pos1 <- data.frame(pos[meta$type =="BLIA",])
pos1$type <- "BLIA"
pos2 <- data.frame(pos[meta$type=="BLIS",])
pos2$type <- "BLIS"
pos3 <- data.frame(pos[meta$type=="LAR",])
pos3$type <- "LAR"
pos4 <- data.frame(pos[meta$type=="MES",])
pos4$type <- "MES"
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 6, fig.width = 8}
library(RColorBrewer)
colors<-c("#8DD3C7","#FFED6F","#BC80BD","#BEBADA","#80B1D3","#FDB462","#B3DE69","#FCCDE5","#FB8072")

# pdf("./Results/TNBC_Subtype_UMAP_AllCelltypes.pdf",width=8,height=6)
DimPlot(SC_harmony, reduction = "umap.harmony", group.by = 'celltype_major',
           label = FALSE, label.size = 5, seed = 2021, pt.size = 0.8)+
  scale_color_manual(values = colors)+
  ggtitle("")
# dev.off()
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 6, fig.width = 8}
# pdf("./Results/TNBC_Subtype_UMAP_AllCelltypes_and_PIPET_Cells.pdf",width=8,height=6)
p <- DimPlot(SC_harmony, reduction = "umap.harmony", group.by = 'celltype_major',
           label = FALSE, label.size = 5, seed = 2021, pt.size = 1)+
  scale_color_manual(values = alpha(colors,0.15))+
  ggtitle("")

p1 <- p+geom_point(aes(x=UMAPharmony_1,y=UMAPharmony_2), alpha = 0.6,
             colour = "#984EA3",size =1.1,data = pos1)
p1 + geom_point(aes(x=UMAPharmony_1,y=UMAPharmony_2), alpha = 0.6,
             colour = "#377EB8",size =1.1,data = pos2)+ 
  geom_point(aes(x=UMAPharmony_1,y=UMAPharmony_2), alpha = 0.6,
             colour = "#E41A1C",size =1.1,data = pos3)+ 
  geom_point(aes(x=UMAPharmony_1,y=UMAPharmony_2), alpha = 0.6,
             colour = "#FF7F00",size =1.1,data = pos4)
# dev.off()
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 6, fig.width = 8}
# pdf("./Results/TNBC_Subtype_UMAP_PIPET_Cells.pdf",width=8,height=6)
DimPlot(SC_harmony, reduction = "umap.harmony", group.by = 'type',
           label = FALSE, label.size = 5, seed = 2021, pt.size = 0.8)+
  scale_color_manual(values = c("#984EA3","#377EB8","#E41A1C","#FF7F00","grey"))+
  ggtitle("")
# dev.off()
```

### Proportion plots

```{r warning=FALSE, echo=FALSE, fig.width =6, fig.height =8}
tmp <- data.frame(Var1=SC1$celltype_major,Var2=SC1$prediction)

tmp$Var1 <- factor(tmp$Var1, levels = c("CAFs", "Cancer Epithelial","Normal Epithelial", "Myeloid",
                                        "T-cells","B-cells","Endothelial","PVL","Plasmablasts"))

p <- ggplot(tmp, aes(x = Var2, group = Var1, fill = Var1)) +
  geom_bar(stat ="count",lwd = 1.5, colour = "white")+        
#    scale_fill_manual(values = c("#E7B800","#8ac926"))+
    labs(x = "",y = "Number of cells")+
    # geom_text(aes(label = tmp$Freq),position=position_dodge(width = 0.8),size =4 ,vjust = -0.45)+  
#    guides(fill = guide_legend(reverse = F))+
    scale_fill_brewer(palette = "Set1") +
    theme_classic()+
    scale_y_continuous(expand=c(0,0))+
    coord_cartesian(ylim = c(0, 2800)) +
    theme(axis.text.x = element_text(size = 13, color = "black",vjust = 0.3),
          axis.text.y = element_text(size = 12, color = "black"),
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16),
          legend.text = element_text(size = 12),
          legend.title=element_blank())
p 
```

### Pie plots

#### BLIA

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
library(stringr)

BLIA <- subset(SC1, subset = prediction %in% c("BLIA"))
tmp1 <- subset(BLIA, subset = celltype_major %in% c("Myeloid"))
tmp2 <- subset(BLIA, subset = celltype_major %in% c("T-cells"))

exceptions <- c("c0_", "c1_", "c2_", "c3_", "c4_", "c5_", "c6_", "c7_", "c8_", "c9_", "c10_", "c11_", "c12_")
regex <- paste0("(", paste(exceptions, collapse = "|"), ")")
tmp1$celltype <- gsub(regex, "", tmp1$celltype_subset)
tmp2$celltype <- gsub(regex, "", tmp2$celltype_subset)

# table(tmp1$celltype_subset,tmp1$prediction)
table(tmp1$celltype,tmp1$prediction)
# table(tmp2$celltype_subset,tmp2$prediction)
table(tmp2$celltype,tmp2$prediction)
```

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
x <- tmp1$celltype
tmp0 <- data.frame(table(x))
tmp0$y <- ifelse(tmp0$Freq>10,levels(tmp0$x),"Others")
tmp <- aggregate(x = tmp0$Freq, by= list(tmp0$y), FUN = sum)
colnames(tmp) <- c("x","Freq")
tmp$percent<- paste(round(100*tmp$Freq/sum(tmp$Freq), 2), "%")
tmp <- tmp[order(tmp$Freq,decreasing = TRUE),]
tmp$celltype <- factor(tmp$x,levels=tmp$x)

library(RColorBrewer)
colors<-brewer.pal(12,'Paired')
# colors<-c("#3f60aa","#44c1f0","#13a983","#9ec417",
#           "#e4ce00","#f18800","#e8490f","#cc340c")

library(ggforce)
p1 <- ggplot()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title=element_blank(), 
        panel.border = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size=18,hjust = 0.5,face="bold"))+
  xlab("")+ylab('')+ ggtitle("BLIA - Myeloid cells") +
  scale_fill_manual(values = colors)+
  geom_arc_bar(data=tmp,
               stat = "pie",
               aes(x0=0,y0=0,r0=1,r=2,
                   amount=Freq,fill=celltype)
  )+
  annotate("text",x=1.53,y=1.45,label="25.46%",angle=-48,size=5)+
  annotate("text",x=1.85,y=-1.1,label="15.96%",angle=55,size=5)+
  annotate("text",x=0.15,y=-2.13,label="14.75%",angle=4,size=5)+
  annotate("text",x=-1.6,y=-1.4,label="13.66%",angle=-47,size=5)+
  annotate("text",x=-2.1,y=0.23,label="13.66%",angle=85,size=5)+
  annotate("text",x=-1.6,y=1.4,label="5.36%",angle=45,size=5)
p1

# pdf("./Results/BLIA_Myeloid_Pie_plot.pdf",width=8,height=6)
# p1
# dev.off()
```

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
x <- tmp2$celltype
tmp0 <- data.frame(table(x))
tmp0$y <- ifelse(tmp0$Freq>10,levels(tmp0$x),"Others")
tmp <- aggregate(x = tmp0$Freq, by= list(tmp0$y), FUN = sum)
colnames(tmp) <- c("x","Freq")
tmp$percent<- paste(round(100*tmp$Freq/sum(tmp$Freq), 2), "%")
tmp <- tmp[order(tmp$Freq,decreasing = TRUE),]
tmp$celltype <- factor(tmp$x,levels=tmp$x)

library(ggforce)
p2 <- ggplot()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title=element_blank(), 
        panel.border = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size=18,hjust = 0.5,face="bold"))+
  xlab("")+ylab('')+ ggtitle("BLIA - T cells") +
  scale_fill_manual(values = colors)+
  geom_arc_bar(data=tmp,
               stat = "pie",
               aes(x0=0,y0=0,r0=1,r=2,
                   amount=Freq,fill=celltype)
  )+
  annotate("text",x=1.5,y=1.5,label="22.89%",angle=-38,size=5)+
  annotate("text",x=1.85,y=-1.0,label="21.07%",angle=55,size=5)+
  annotate("text",x=-0.5,y=-2.05,label="18.25%",angle=-18,size=5)+
  annotate("text",x=-1.9,y=-0.9,label="10.27%",angle=-63,size=5)+
  annotate("text",x=-2.1,y=0.2,label="7.92%",angle=85,size=5)+
  annotate("text",x=-1.78,y=1.15,label="7.16%",angle=60,size=5)
p2

# pdf("./Results/BLIA_TCells_Pie_plot.pdf",width=8,height=6)
# p2
# dev.off()
```

#### MES

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
MES <- subset(SC1, subset = prediction %in% c("MES"))
tmp1 <- subset(MES, subset = celltype_major %in% c("CAFs"))

tmp1$celltype <- gsub("[ ]", "_", tmp1$celltype_subset)
# table(tmp1$celltype_subset,tmp1$prediction)
table(tmp1$celltype,tmp1$prediction)
```

```{r warning=FALSE, echo=FALSE, fig.width =7.6, fig.height =6}
x <- tmp1$celltype
tmp0 <- data.frame(table(x))
tmp0$y <- ifelse(tmp0$Freq>10,levels(tmp0$x),"Others")
tmp <- aggregate(x = tmp0$Freq, by= list(tmp0$y), FUN = sum)
colnames(tmp) <- c("x","Freq")
tmp$percent<- paste(round(100*tmp$Freq/sum(tmp$Freq), 2), "%")
tmp <- tmp[order(tmp$Freq,decreasing = TRUE),]
tmp$celltype <- factor(tmp$x,levels=tmp$x)

p3 <- ggplot()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title=element_blank(), 
        panel.border = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size=18,hjust = 0.5,face="bold"))+
  xlab("")+ylab('')+ ggtitle("MES - CAFs") +
  scale_fill_manual(values = colors)+
  geom_arc_bar(data=tmp,
               stat = "pie",
               aes(x0=0,y0=0,r0=1,r=2,
                   amount=Freq,fill=celltype)
  )+
  annotate("text",x=2.1,y=0.2,label="49.37%",angle=-85,size=5)+
  annotate("text",x=-1.4,y=-1.6,label="20.67%",angle=-40,size=5)+
  annotate("text",x=-2.1,y=0.2,label="12.32%",angle=85,size=5)+
  annotate("text",x=-1.55,y=1.45,label="10.54%",angle=52,size=5)+
  annotate("text",x=-0.45,y=2.05,label="7.10%",angle=13,size=5)
p3

# pdf("./Results/MES_CAFs_Pie_plot.pdf",width=7.9,height=6)
# p3
# dev.off()
```

### DE genes

```{r warning=FALSE, echo=FALSE, fig.width =8, fig.height =6}
DefaultAssay(SC1) <- "RNA"
Idents(SC1)="prediction"

#find markers for every cluster compared to all remaining cells, report only the positive ones
SC.markers <- FindAllMarkers(SC1, only.pos = TRUE, 
                             min.pct = 0.25, logfc.threshold = 0.25)

biomarkers <- SC.markers %>%
  dplyr::filter(p_val_adj<0.05) %>%
  group_by(cluster) %>%
  slice_max(n = 20000, order_by = avg_log2FC)

# Basal <- biomarkers %>% dplyr::filter(cluster=="Basal") %>%
#   dplyr::filter(avg_log2FC>=2)
# Her2 <- biomarkers %>% dplyr::filter(cluster=="Her2") %>%
#   dplyr::filter(avg_log2FC>=2)
# LumA <- biomarkers %>% dplyr::filter(cluster=="LumA") %>%
#   dplyr::filter(avg_log2FC>=2)
# LumB <- biomarkers %>% dplyr::filter(cluster=="LumB") %>%
#   dplyr::filter(avg_log2FC>=2)

tmp <- biomarkers %>% 
  dplyr::filter(avg_log2FC>=3)
write.xlsx(tmp, "./Results/TNBC_Subtype_biomarkers_pos_FDR0.05_orderByavglog2FC.xlsx")
```

### GSEA by using KEGG genesets

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 4, fig.width = 9}
library(fgsea)
library(msigdbr)
library(openxlsx)
library(clusterProfiler)
library(enrichplot)

mdb_c2 <- msigdbr(species = "Homo sapiens", category = "C2")
mdb_kegg = mdb_c2 [grep("^KEGG",mdb_c2 $gs_name),]
# fgsea_sets = mdb_kegg %>% split(x = .$gene_symbol, f = .$gs_name)
MSigDB <- data.frame(term=mdb_kegg$gs_name,gene=mdb_kegg$gene_symbol)
MSigDB$term <- gsub('[_]', ' ', MSigDB$term)
MSigDB$term <- str_replace(MSigDB$term, "KEGG ","")
MSigDB$term <- str_replace(MSigDB$term, "CYTOKINE CYTOKINE ","CYTOKINE-CYTOKINE")

biomarkers1 <- SC.markers %>%
  dplyr::filter(p_val_adj<0.05) %>%
  dplyr::filter(avg_log2FC>=1)

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("BLIA"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp1 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp1$Subtype <- "BLIA"

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("BLIS"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp2 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp2$Subtype <- "BLIS"

data <- biomarkers1 
data$log2fc <- ifelse(data$cluster %in% c("LAR"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp3 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp3$Subtype <- "LAR"

data <- biomarkers1 
data$log2fc <- ifelse(data$cluster %in% c("MES"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp4 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp4$Subtype <- "MES"
 
tmp <- rbind(tmp1,tmp2,tmp3,tmp4)  
tmp$num <- 1:nrow(tmp)
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 8, fig.width = 9}
p <- ggplot(tmp, aes(reorder(ID, -num), NES,fill= Subtype)) +
  geom_bar(stat ="identity",width = 0.8,position = position_dodge(width=0.8))+ 
#  scale_fill_gradient(low = "#156077", high = "#f46f20")+
  scale_fill_brewer(palette = 'Set1')+
  coord_flip() +
  labs(x="")+
  theme_bw()+
  # theme_classic()+
    theme(#panel.grid.major.x = element_line(color = "grey"), 
          panel.grid = element_blank(),
          axis.text.x = element_text(size = 13, color = "black"),
          axis.text.y = element_text(size = 12, color = "black"),
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16),
          legend.text = element_text(size = 12), 
          legend.title = element_blank())
p

# pdf(file.path("./Results/TNBC_Subtype_KEGG_pathway.pdf"),width = 10,height = 8)
# p
# dev.off()
```

### GSEA by using HALLMARK genesets

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 8, fig.width = 9}
library(clusterProfiler)
library(enrichplot)

MSigDB=read.gmt("h.all.v2023.1.Hs.symbols.gmt")
MSigDB$term <- str_replace(MSigDB$term, "HALLMARK_","")
MSigDB$term <- str_replace_all(MSigDB$term, "_"," ")

biomarkers1 <- SC.markers %>%
  dplyr::filter(p_val_adj<0.05) %>%
  dplyr::filter(avg_log2FC>=1)

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("BLIA"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp1 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp1$Subtype <- "BLIA"

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("BLIS"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp2 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp2$Subtype <- "BLIS"

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("LAR"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp3 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp3$Subtype <- "LAR"

data <- biomarkers1
data$log2fc <- ifelse(data$cluster %in% c("MES"),data$avg_log2FC,-data$avg_log2FC)
geneList <- data$log2fc
names(geneList) <- data$gene
geneList <- sort(geneList,decreasing = T)
GSEA.data <- GSEA(geneList = geneList,TERM2GENE=MSigDB,seed = T,verbose=F,pvalueCutoff = 0.25)
tmp4 <- GSEA.data@result %>% 
  arrange(desc(NES)) %>% 
  filter(NES>0)
tmp4$Subtype <- "MES"
 
tmp <- rbind(tmp1,tmp2,tmp3,tmp4)  
tmp$num <- 1:nrow(tmp)
```

```{r warning=FALSE, echo=FALSE, message=FALSE, fig.height = 8, fig.width = 9}
p <- ggplot(tmp, aes(reorder(ID, -num), NES,fill= Subtype)) +
  geom_bar(stat ="identity",width = 0.8,position = position_dodge(width=0.8))+ 
#  scale_fill_gradient(low = "#156077", high = "#f46f20")+
  scale_fill_brewer(palette = 'Set1')+
  coord_flip() +
  labs(x="")+
  theme_bw()+
  # theme_classic()+
    theme(#panel.grid.major.x = element_line(color = "grey"), 
          panel.grid = element_blank(),
          axis.text.x = element_text(size = 13, color = "black"),
          axis.text.y = element_text(size = 12, color = "black"),
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16),
          legend.text = element_text(size = 12), 
          legend.title = element_blank())
p

# pdf(file.path("./Results/TNBC_Subtype_GSEA_pathway.pdf"),width = 9,height = 8)
# p
# dev.off()
```
