#' @title Drawing survival curves for different risk groups
#' @description It is a function to plot survival curves. First, calculate the risk score of each sample based on the results of multi-factor cox
#'     regression analysis. The sample will then be divided into high and low risk groups based on the median value of the risk score. And plot
#'     a list of survfit objects as generated by the Surv function.
#'
#' @param data A data frame with clinical information of the data to be analyzed.
#' @param genes A set of genes contained in the "data."
#' @param surv_cols A vector containing variable names for survival status and survival time. And they must be contained in the "data" columns.
#' @param coxph An object of class coxph representing the fit (output by coxph function).
#' @param time A string value to indicate how to store the survival time (days or months). The default value is days.
#' @param xlim An integer, set limits for the x axis.
#' @param break.time The numeric value controlling time axis breaks. Default value is 30.
#' @param legend.title Set a legend title.
#' @param legend.labs Character vector specifying legend labels. Used to replace the names of the strata from the fit.
#' @param pval It is used to control the display of p-values for comparisons between survival curves. The default value is TRUE.
#' @param conf.int It is used to control the display of confidence intervals around the survival curves in a Kaplan-Meier plot. The default value is FALSE.
#' @param palette The argument palette can be used to specify the color to be used for each group. The default value is "simpsons".
#'
#' @return An output of graphic or a list of ggsurvplot object.
#'
#' @import survival survminer tidyverse
#' @export
#'
#' @examples # Please refer to vignette.
PIPET_KM <- function(data, genes, surv_cols, coxph,time="days",
                     xlim=120,break.time=30,legend.title, legend.labs = c("HRisk", "LRisk"),
                     pval = TRUE, conf.int = FALSE,palette = "simpsons"){
  library(survival)
  library(survminer)
  library(tidyverse)

  info <- data[,surv_cols]
  for (gene in genes) {
    tmp <- data[,gene]*(summary(coxph)$coefficients[gene,1])
    info <- cbind(info,tmp)
  }
  info$RiskScore <- exp(rowSums(info[,3:ncol(info)]))
  info$RiskGroup <- ifelse(info$RiskScore >= median(info$RiskScore),'HRisk','LRisk')

  if(!(time %in% c("days","months")))
    stop("Please check, OS time must be stored by days or months.")
  if(time=="days"){
    fit <- survfit(Surv(round(futime/30.5,4), fustat) ~ RiskGroup, data = info, type = "kaplan-meier",
                   error = "greenwood", conf.type = "plain", na.action = na.exclude)
  }else{
    fit <- survfit(Surv(round(futime,4), fustat) ~ RiskGroup, data = info, type = "kaplan-meier",
                   error = "greenwood", conf.type = "plain", na.action = na.exclude)
  }

  ggsurv <- ggsurvplot(fit, data = info,
                       surv.median.line = "h", # Add medians survival
                       xlim = c(0, xlim),
                       break.time.by = break.time,
                       font.tickslab = c(12),
                       font.x = c(14),
                       font.y = c(14),

                       # Change legends: title & labels
                       legend.title = legend.title,
                       legend.labs = legend.labs,
                       font.legend = c(12),
                       # Add p-value and tervals
                       pval = pval,
                       conf.int = conf.int,
                       # Add risk table
                       risk.table = TRUE,
                       tables.height = 0.2,
                       risk.table.col = "strata",
                       risk.table.y.text = FALSE,

                       # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                       # or brewer color (e.g. "Dark2"), or ggsci color (e.g. "jco")
                       palette = palette,
                       ggtheme = theme_classic()
  )
  ggsurv$table <- ggsurv$table + labs(y = NULL) +
    theme(axis.text.x = element_text(size = 12),
          axis.title.x = element_text(size = 14))
  ggsurv

  return(ggsurv)
}
